name: Deploy app on App Engine

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Start continuous deployment
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'cd:')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: app.yaml
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials: ${{ secrets.GCP_SA_KEY_JSON }}
      # - uses: google-github-actions/setup-gcloud@v0.2.0
      #   with:
      #     project_id: ${{ secrets.gcp_project }}
      #     service_account_key: ${{ secrets.gcp_credentials }}
      #     export_default_credentials: true

      - name: verificando versão do node.js
        run: node --version
      
      - name: deploy to app engine
        run: gcloud app deploy





