name: Deploy app on App Engine

on:
  push:
    branches: [main]

env:
  TESTE: joao

jobs:
  deploy:
    name: Start continuous deployment
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message('deploy:'))"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: verificando versão do node.js
        run: node --version





